services:
  - type: web
    name: ask-your-documents-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: LLM_PROVIDER
        value: openrouter
      - key: OPENROUTER_API_KEY
        sync: false # You will enter this value manually in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.4
    plan: free
